version: "3.7"
services:
  app:
    build: .
    expose:
      - 8000
    environment:
      LRC_DATABASE_ALLOWED_HOSTS: ${LRC_DATABASE_ALLOWED_HOSTS}
      LRC_DATABASE_DEBUG: 0
      LRC_DATABASE_SECRET_KEY: ${LRC_DATABASE_SECRET_KEY}
      PYTHONDONTWRITEBYTECODE: 1
    volumes:
      - ./lrc_database/db.sqlite3:/srv/db/db.sqlite3
      - static-content:/srv/static
    restart: always
  proxy:
    build: ./nginx
    ports:
      - 8000:8000
    depends_on:
      - app
    volumes:
      - static-content:/srv/static
    restart: always
volumes:
  static-content:
