version: "3.7"
services:
  app:
    build: .
    volumes:
      - ./lrc_database:/srv
    command: python manage.py runserver 0.0.0.0:8000
    expose:
      - 8000
  proxy:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - app
  db:
    build: ./postgres
    expose:
      - 5432
    environment:
      POSTGRES_PASSWORD: abc123
