version: "3.7"
services:
  app:
    build: .
    volumes:
      - ./lrc_database:/srv
    command: python manage.py runserver 0.0.0.0:8000
    expose:
      - 8000
    environment:
      PYTHONDONTWRITEBYTECODE: 1
  proxy:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - app
