# Generated by Django 4.1.7 on 2023-03-19 22:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shift",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="shift",
            name="duration",
            field=models.DurationField(
                help_text="How long the shift will last. Format: HH:MM. E.g. if you want shift to be 1 hour 15 mins long, enter 01:15"
            ),
        ),
    ]
