# Generated by Django 4.1.5 on 2023-02-12 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffuserposition",
            name="hourly_rate",
            field=models.DecimalField(
                decimal_places=2, help_text="Hourly rate for this position for this person.", max_digits=6
            ),
        ),
    ]
