# Generated by Django 4.1.5 on 2023-02-12 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_staffuserposition_hourly_rate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lrcdatabaseuser",
            name="first_name",
            field=models.CharField(max_length=100, verbose_name="first name"),
        ),
        migrations.AlterField(
            model_name="lrcdatabaseuser",
            name="last_name",
            field=models.CharField(max_length=100, verbose_name="last name"),
        ),
    ]
