# Generated by Django 4.1.7 on 2023-03-25 13:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_alter_lrcdatabaseuser_email"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lrcdatabaseuser",
            options={"ordering": ("first_name", "last_name", "email")},
        ),
        migrations.AlterField(
            model_name="shift",
            name="kind",
            field=models.CharField(
                choices=[
                    ("SI", "SI"),
                    ("Tutoring", "Tutoring"),
                    ("Group Tutoring", "Group Tutoring"),
                    ("Training", "Training"),
                    ("Observation", "Observation"),
                    ("Class", "Class"),
                    ("Preparation", "Preparation"),
                    ("Meeting", "Meeting"),
                    ("Other", "Other"),
                ],
                help_text="The kind of shift this is: tutoring, SI, Training, Class, or Observation.",
                max_length=14,
            ),
        ),
    ]
