# Generated by Django 4.1.5 on 2023-02-12 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_lrcdatabaseuser_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lrcdatabaseuser",
            name="email",
            field=models.EmailField(max_length=100, verbose_name="email"),
        ),
    ]
