# Generated by Django 4.1.7 on 2023-03-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_alter_lrcdatabaseuser_options_alter_shift_kind"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shift",
            name="kind",
            field=models.CharField(
                choices=[
                    ("SI", "SI"),
                    ("Tutoring", "Tutoring"),
                    ("Group Tutoring", "Group Tutoring"),
                    ("Training", "Training"),
                    ("Observation", "Observation"),
                    ("Class", "Class"),
                    ("Preparation", "Preparation"),
                    ("Meeting", "Meeting"),
                    ("OURS Mentor", "OURS Mentor"),
                    ("Other", "Other"),
                ],
                help_text="The kind of shift this is: tutoring, SI, Training, Class, or Observation.",
                max_length=14,
            ),
        ),
        migrations.AlterField(
            model_name="shiftchangerequest",
            name="new_kind",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SI", "SI"),
                    ("Tutoring", "Tutoring"),
                    ("Group Tutoring", "Group Tutoring"),
                    ("Training", "Training"),
                    ("Observation", "Observation"),
                    ("Class", "Class"),
                    ("Preparation", "Preparation"),
                    ("Meeting", "Meeting"),
                    ("OURS Mentor", "OURS Mentor"),
                    ("Other", "Other"),
                ],
                default=None,
                help_text="The kind of shift this is: tutoring or SI.",
                max_length=14,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="staffuserposition",
            name="position",
            field=models.CharField(
                choices=[
                    ("SI", "SI"),
                    ("Tutor", "Tutor"),
                    ("PM", "PM"),
                    ("GT", "Group-Tutor"),
                    ("OursM", "OURS-Mentor"),
                ],
                max_length=5,
            ),
        ),
    ]
