# Generated by Django 4.1.7 on 2023-03-30 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_alter_shift_kind_alter_shiftchangerequest_new_kind_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AllFiles",
            fields=[
                ("doc_id", models.AutoField(primary_key=True, serialize=False)),
                ("document", models.FileField(upload_to="document/")),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="fullcourse",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="staffuserposition",
            name="si_course",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lrc_database_user_si_course",
                to="main.fullcourse",
                verbose_name="SI/Group-Tutor course",
            ),
        ),
        migrations.AddField(
            model_name="shift",
            name="document",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="Any pdf documnet you want to share for this shift.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="main.allfiles",
            ),
        ),
        migrations.AddField(
            model_name="shiftchangerequest",
            name="document",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="Any pdf documnet you want to share for this shift change request.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="main.allfiles",
            ),
        ),
    ]
