# Generated by Django 4.1.7 on 2023-03-31 18:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_allfiles_alter_fullcourse_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shiftchangerequest",
            name="document",
        ),
        migrations.AlterField(
            model_name="shift",
            name="document",
            field=models.FileField(
                blank=True,
                default=None,
                help_text="Any pdf documnet you want to share for this shift.",
                null=True,
                upload_to="documents/",
                validators=[django.core.validators.FileExtensionValidator(allowed_extensions=["pdf"])],
            ),
        ),
        migrations.DeleteModel(
            name="AllFiles",
        ),
    ]
