# Generated by Django 4.1.7 on 2023-09-04 11:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0011_punchedin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffuserposition",
            name="position",
            field=models.CharField(
                choices=[
                    ("SI", "SI"),
                    ("Tutor", "Tutor"),
                    ("PM", "PM"),
                    ("GT", "Group-Tutor"),
                    ("OursM", "OURS-Mentor"),
                    ("OA", "Office Assistant"),
                    ("Tech", "Tech"),
                    ("Other", "Other"),
                ],
                max_length=5,
            ),
        ),
    ]
