# Generated by Django 4.1.7 on 2023-09-04 12:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0012_alter_staffuserposition_position"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shift",
            name="kind",
            field=models.CharField(
                choices=[
                    ("SI", "SI"),
                    ("Tutor Drop In", "Tutor Drop In"),
                    ("Tutor Appointment", "Tutor Appointment"),
                    ("Group Tutoring", "Group Tutoring"),
                    ("Training", "Training"),
                    ("Observation", "Observation"),
                    ("Class", "Class"),
                    ("Preparation", "Preparation"),
                    ("Meeting", "Meeting"),
                    ("OURS Mentor", "OURS Mentor"),
                    ("OA Hours", "OA Hours"),
                    ("Other", "Other"),
                ],
                help_text="The kind of shift this is: tutoring, SI, Training, Class, or Observation.",
                max_length=20,
            ),
        ),
    ]
