# Generated by Django 3.2.21 on 2023-09-24 22:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_lrcdatabaseuser_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(help_text='The start date of the week for which you are assigning this payroll check.')),
                ('approved', models.BooleanField(default=False, help_text='Is this payroll entered on HR website yet?')),
                ('pay_details', models.JSONField(default=dict)),
                ('additional_pay_details', models.JSONField(default=dict)),
                ('person', models.ForeignKey(help_text='The person whome you want to assign a payroll check.', on_delete=django.db.models.deletion.CASCADE, related_name='payroll_check_for_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('week_start', 'person'),
                'unique_together': {('person', 'week_start')},
            },
        ),
    ]
